// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeScreenshot(arg1, arg2) {
  return window['go']['main']['App']['AnalyzeScreenshot'](arg1, arg2);
}

export function CheckOllamaStatus() {
  return window['go']['main']['App']['CheckOllamaStatus']();
}

export function DeleteScreenshot(arg1) {
  return window['go']['main']['App']['DeleteScreenshot'](arg1);
}

export function GetScreenshotBase64(arg1) {
  return window['go']['main']['App']['GetScreenshotBase64'](arg1);
}

export function GetScreenshots() {
  return window['go']['main']['App']['GetScreenshots']();
}

export function TakeScreenshot(arg1) {
  return window['go']['main']['App']['TakeScreenshot'](arg1);
}
