// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AnalyzeScreenshot(arg1:string,arg2:string):Promise<main.AnalysisResult>;

export function CheckOllamaStatus():Promise<{[key: string]: any}>;

export function DeleteScreenshot(arg1:string):Promise<main.ScreenshotResult>;

export function GetScreenshotBase64(arg1:string):Promise<string>;

export function GetScreenshots():Promise<Array<main.ScreenshotInfo>>;

export function TakeScreenshot(arg1:string):Promise<main.ScreenshotResult>;
